### ISSUE TITLE
動作環境についての報告

### ISSUE THREAD

**Issue by tokohito** [mzyy94/ns-remote#3]
数日触ってみていくつか懸案ないし課題が出てきたのですが、どのようにお伝えするのが適当か分からなかったので一旦単一のIssueで書かせていただきます。
必要があれば分割して再度起票しますので仰ってください。

1. ブラウザの相性
Android 11のChromeブラウザで接続すると表示はできるものの仮想コントローラーが反応せず、音声も出力されません。Windows10のFirefox/Chromeの場合は仮想コントローラー操作も音声も問題ありませんが、最初にns-remoteへアクセスした際PeerConnectionが成立するまで30～60秒ほど遅れがあります。(いづれもpion/webrtc側の問題かもしれませんが…)
iPhone 7(iOS14.4)のSafariブラウザは問題ありません。
2. スリープ復帰時の挙動
Switch本体を一度スリープしてから復帰した場合は v4l2-ctl --set-dv-bt-timings query を実行しないと映像/音声が転送されません(ログを見る限りWebRTCのネゴシエーションは開始されている様子)。もし次期バージョンアップでこの手順をスキップできるようになるとありがたいです。
3. 音声が稀に出力されない
稀に映像の転送と仮想コントローラー操作が出来てるにもかかわらず音声が出力されない場合があります(ns-remote起動時ALSAデバイスのアタッチ指定済)。この状態になるとブラウザの再起動やns-remoteの再実行でも解消しないので一度スリープしてから復帰させることで解消できるようです(上記の通りスリープ復帰直後--set-dv-bt-timingsを再実行してますが関連は不明)。
4. スリープ復帰機能
READMEにも書かれていらっしゃるので恐らく構想としてはあると思うのですが、ns-remote経由でスリープ解除ができると大変嬉しいです。
5. キーボード認識
PCのブラウザからns-remoteにアクセス操作するスタイルが多いのですが、仮想HIDキーボードをスイッチにアタッチするなどして手元キーボードからの操作/文字入力ができると大変うれしいです(Onlineのパスワード入力がキーボードでできると捗りそうです)。

散逸な文章になってしまい申し訳ありません、お時間のある時にお返事いただけますと幸いです。

**Comment by tokohito** [comment]
> 音声が稀に出力されない

すいません、こちらの症状ですが私の勘違いでした。
Windows10のFirefox/Chromeからアクセスした際に物理コントローラーで操作を始めると上記の症状が発生しますが、ブラウザ上の仮想コントローラーで操作すると音声が出力されることを確認しました。
仮想コントローラー操作で音声が出力された後は物理コントローラーに持ち替えて操作しても音声は引き続き出力されるので、接続開始時の問題のようです。

**Comment by mzyy94** [comment]
> 1. ブラウザの相性

Android Chromeは確かに挙動が優れないことがあったので、コネクション確立に問題があるのもありそうですね。
ちょっとこちらは原因が即座には掴めないので、一つIssueとして切り出しておいてもらえると嬉しいです。

> 2. スリープ復帰時の挙動

READMEの通り、これは毎回毎回必要な操作のため、ご容赦ください🙇‍♂️
https://github.com/mzyy94/ns-remote#h2c-rpi-b01-board


> 3. 音声が稀に出力されない

これは動画の自動再生の都合でこうなってます💦
モダンブラウザではユーザー操作がない状態で音声を再生させる方法がないため、画面タップ操作をトリガーとして音声出力ができる状態になるよう実装している都合によるもので、仕様となります。

> 4. スリープ復帰機能

こればかりはLinuxのカーネルモジュールのレベルでwake-upの信号を出すことができないようなので、すぐの対応は難しいと思います😅

> 5. キーボード認識

LinuxのUSB Gadgetのエミュレーションは1ポートにつき1デバイスが上限のため、同時接続は難しいです。
切り替えて接続させる方法も考えられますが、キー入力があるタイミングでキーボードを仮想デバイスとしてSwitchに接続すると、そのタイミングでコントローラーが外れてしまい、その都度切断・接続処理を繰り返すのは現実的ではないこともあり、このプロジェクト内での解決はしない方向としておきます。
どうしてもという場合は、もう一台のRaspberry Piを用意し、そちらでUSB Gadgetでキーボードをエミュレーションし、ブラウザからHTTPやWebSocket等のプロトコルで送信し、入力を担わせるような実装をして代替してみることを提案しておきます。

**Comment by tokohito** [comment]
返信いただいていたのに気が付きませんでした、申し訳ありません🙇

丁寧に回答いただきありがとうございます、了解いたしました。
1のブラウザの相性については別途issue起票しますのでよろしくお願いいたします。
